#! /bin/python

import argparse

parser = argparse.ArgumentParser(description='GoList to C++ compiler')

parser.add_argument('-v', '--verbose', action='store_true', help='Verbose')
parser.add_argument('-p', '--pptype', action='store_true', help='Pretty print the input program with types of expressions in the comments')
parser.add_argument('-d', '--dumpsymtab', action='store_true', help='Dump the symbol table after the end of each scope')

parser.add_argument('-o', type=str, help='Name of the output file')

args = parser.parse_args()

pptype = False
dumpsymtab = False
if args.pptype:
	pptype = True
if args.dumpsymtab:
	dumpsymtab = True