/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.parser;

import goplusplus.node.*;
import goplusplus.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTBreak(@SuppressWarnings("unused") TBreak node)
    {
        this.index = 0;
    }

    @Override
    public void caseTDefault(@SuppressWarnings("unused") TDefault node)
    {
        this.index = 1;
    }

    @Override
    public void caseTFunc(@SuppressWarnings("unused") TFunc node)
    {
        this.index = 2;
    }

    @Override
    public void caseTInterface(@SuppressWarnings("unused") TInterface node)
    {
        this.index = 3;
    }

    @Override
    public void caseTSelect(@SuppressWarnings("unused") TSelect node)
    {
        this.index = 4;
    }

    @Override
    public void caseTCase(@SuppressWarnings("unused") TCase node)
    {
        this.index = 5;
    }

    @Override
    public void caseTDefer(@SuppressWarnings("unused") TDefer node)
    {
        this.index = 6;
    }

    @Override
    public void caseTGo(@SuppressWarnings("unused") TGo node)
    {
        this.index = 7;
    }

    @Override
    public void caseTMap(@SuppressWarnings("unused") TMap node)
    {
        this.index = 8;
    }

    @Override
    public void caseTStruct(@SuppressWarnings("unused") TStruct node)
    {
        this.index = 9;
    }

    @Override
    public void caseTChan(@SuppressWarnings("unused") TChan node)
    {
        this.index = 10;
    }

    @Override
    public void caseTElse(@SuppressWarnings("unused") TElse node)
    {
        this.index = 11;
    }

    @Override
    public void caseTGoto(@SuppressWarnings("unused") TGoto node)
    {
        this.index = 12;
    }

    @Override
    public void caseTPackage(@SuppressWarnings("unused") TPackage node)
    {
        this.index = 13;
    }

    @Override
    public void caseTSwitch(@SuppressWarnings("unused") TSwitch node)
    {
        this.index = 14;
    }

    @Override
    public void caseTConst(@SuppressWarnings("unused") TConst node)
    {
        this.index = 15;
    }

    @Override
    public void caseTFallthrough(@SuppressWarnings("unused") TFallthrough node)
    {
        this.index = 16;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 17;
    }

    @Override
    public void caseTRange(@SuppressWarnings("unused") TRange node)
    {
        this.index = 18;
    }

    @Override
    public void caseTType(@SuppressWarnings("unused") TType node)
    {
        this.index = 19;
    }

    @Override
    public void caseTContinue(@SuppressWarnings("unused") TContinue node)
    {
        this.index = 20;
    }

    @Override
    public void caseTFor(@SuppressWarnings("unused") TFor node)
    {
        this.index = 21;
    }

    @Override
    public void caseTImport(@SuppressWarnings("unused") TImport node)
    {
        this.index = 22;
    }

    @Override
    public void caseTReturn(@SuppressWarnings("unused") TReturn node)
    {
        this.index = 23;
    }

    @Override
    public void caseTVar(@SuppressWarnings("unused") TVar node)
    {
        this.index = 24;
    }

    @Override
    public void caseTBasicTypes(@SuppressWarnings("unused") TBasicTypes node)
    {
        this.index = 25;
    }

    @Override
    public void caseTPrint(@SuppressWarnings("unused") TPrint node)
    {
        this.index = 26;
    }

    @Override
    public void caseTPrintln(@SuppressWarnings("unused") TPrintln node)
    {
        this.index = 27;
    }

    @Override
    public void caseTAppend(@SuppressWarnings("unused") TAppend node)
    {
        this.index = 28;
    }

    @Override
    public void caseTBoolLit(@SuppressWarnings("unused") TBoolLit node)
    {
        this.index = 29;
    }

    @Override
    public void caseTAdd(@SuppressWarnings("unused") TAdd node)
    {
        this.index = 30;
    }

    @Override
    public void caseTSub(@SuppressWarnings("unused") TSub node)
    {
        this.index = 31;
    }

    @Override
    public void caseTMul(@SuppressWarnings("unused") TMul node)
    {
        this.index = 32;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 33;
    }

    @Override
    public void caseTMod(@SuppressWarnings("unused") TMod node)
    {
        this.index = 34;
    }

    @Override
    public void caseTBitAnd(@SuppressWarnings("unused") TBitAnd node)
    {
        this.index = 35;
    }

    @Override
    public void caseTBitOr(@SuppressWarnings("unused") TBitOr node)
    {
        this.index = 36;
    }

    @Override
    public void caseTCaret(@SuppressWarnings("unused") TCaret node)
    {
        this.index = 37;
    }

    @Override
    public void caseTLshift(@SuppressWarnings("unused") TLshift node)
    {
        this.index = 38;
    }

    @Override
    public void caseTRshift(@SuppressWarnings("unused") TRshift node)
    {
        this.index = 39;
    }

    @Override
    public void caseTBitclear(@SuppressWarnings("unused") TBitclear node)
    {
        this.index = 40;
    }

    @Override
    public void caseTPluseq(@SuppressWarnings("unused") TPluseq node)
    {
        this.index = 41;
    }

    @Override
    public void caseTSubeq(@SuppressWarnings("unused") TSubeq node)
    {
        this.index = 42;
    }

    @Override
    public void caseTMuleq(@SuppressWarnings("unused") TMuleq node)
    {
        this.index = 43;
    }

    @Override
    public void caseTDiveq(@SuppressWarnings("unused") TDiveq node)
    {
        this.index = 44;
    }

    @Override
    public void caseTModeq(@SuppressWarnings("unused") TModeq node)
    {
        this.index = 45;
    }

    @Override
    public void caseTAndeq(@SuppressWarnings("unused") TAndeq node)
    {
        this.index = 46;
    }

    @Override
    public void caseTOreq(@SuppressWarnings("unused") TOreq node)
    {
        this.index = 47;
    }

    @Override
    public void caseTXoreq(@SuppressWarnings("unused") TXoreq node)
    {
        this.index = 48;
    }

    @Override
    public void caseTLshifteq(@SuppressWarnings("unused") TLshifteq node)
    {
        this.index = 49;
    }

    @Override
    public void caseTRshifteq(@SuppressWarnings("unused") TRshifteq node)
    {
        this.index = 50;
    }

    @Override
    public void caseTBitcleareq(@SuppressWarnings("unused") TBitcleareq node)
    {
        this.index = 51;
    }

    @Override
    public void caseTAnd(@SuppressWarnings("unused") TAnd node)
    {
        this.index = 52;
    }

    @Override
    public void caseTOr(@SuppressWarnings("unused") TOr node)
    {
        this.index = 53;
    }

    @Override
    public void caseTReceive(@SuppressWarnings("unused") TReceive node)
    {
        this.index = 54;
    }

    @Override
    public void caseTIncrement(@SuppressWarnings("unused") TIncrement node)
    {
        this.index = 55;
    }

    @Override
    public void caseTDecrement(@SuppressWarnings("unused") TDecrement node)
    {
        this.index = 56;
    }

    @Override
    public void caseTEq(@SuppressWarnings("unused") TEq node)
    {
        this.index = 57;
    }

    @Override
    public void caseTLt(@SuppressWarnings("unused") TLt node)
    {
        this.index = 58;
    }

    @Override
    public void caseTGt(@SuppressWarnings("unused") TGt node)
    {
        this.index = 59;
    }

    @Override
    public void caseTAssign(@SuppressWarnings("unused") TAssign node)
    {
        this.index = 60;
    }

    @Override
    public void caseTNot(@SuppressWarnings("unused") TNot node)
    {
        this.index = 61;
    }

    @Override
    public void caseTNoteq(@SuppressWarnings("unused") TNoteq node)
    {
        this.index = 62;
    }

    @Override
    public void caseTLeq(@SuppressWarnings("unused") TLeq node)
    {
        this.index = 63;
    }

    @Override
    public void caseTGeq(@SuppressWarnings("unused") TGeq node)
    {
        this.index = 64;
    }

    @Override
    public void caseTShortdecl(@SuppressWarnings("unused") TShortdecl node)
    {
        this.index = 65;
    }

    @Override
    public void caseTVarargs(@SuppressWarnings("unused") TVarargs node)
    {
        this.index = 66;
    }

    @Override
    public void caseTLeftpar(@SuppressWarnings("unused") TLeftpar node)
    {
        this.index = 67;
    }

    @Override
    public void caseTLeftsq(@SuppressWarnings("unused") TLeftsq node)
    {
        this.index = 68;
    }

    @Override
    public void caseTLeftcurl(@SuppressWarnings("unused") TLeftcurl node)
    {
        this.index = 69;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 70;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 71;
    }

    @Override
    public void caseTRightpar(@SuppressWarnings("unused") TRightpar node)
    {
        this.index = 72;
    }

    @Override
    public void caseTRightsq(@SuppressWarnings("unused") TRightsq node)
    {
        this.index = 73;
    }

    @Override
    public void caseTRightcurl(@SuppressWarnings("unused") TRightcurl node)
    {
        this.index = 74;
    }

    @Override
    public void caseTSemi(@SuppressWarnings("unused") TSemi node)
    {
        this.index = 75;
    }

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 76;
    }

    @Override
    public void caseTIntLit(@SuppressWarnings("unused") TIntLit node)
    {
        this.index = 77;
    }

    @Override
    public void caseTFloatLit(@SuppressWarnings("unused") TFloatLit node)
    {
        this.index = 78;
    }

    @Override
    public void caseTRuneLit(@SuppressWarnings("unused") TRuneLit node)
    {
        this.index = 79;
    }

    @Override
    public void caseTStringLit(@SuppressWarnings("unused") TStringLit node)
    {
        this.index = 80;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 81;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 82;
    }
}
