/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.node;

import goplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AAppendAstExp extends PAstExp
{
    private TId _id_;
    private PAstExp _astExp_;

    public AAppendAstExp()
    {
        // Constructor
    }

    public AAppendAstExp(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PAstExp _astExp_)
    {
        // Constructor
        setId(_id_);

        setAstExp(_astExp_);

    }

    @Override
    public Object clone()
    {
        return new AAppendAstExp(
            cloneNode(this._id_),
            cloneNode(this._astExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAppendAstExp(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PAstExp getAstExp()
    {
        return this._astExp_;
    }

    public void setAstExp(PAstExp node)
    {
        if(this._astExp_ != null)
        {
            this._astExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._astExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._astExp_ == child)
        {
            this._astExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._astExp_ == oldChild)
        {
            setAstExp((PAstExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
