/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.node;

import goplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AArrayAccessAstExp extends PAstExp
{
    private PAstExp _array_;
    private PAstExp _index_;

    public AArrayAccessAstExp()
    {
        // Constructor
    }

    public AArrayAccessAstExp(
        @SuppressWarnings("hiding") PAstExp _array_,
        @SuppressWarnings("hiding") PAstExp _index_)
    {
        // Constructor
        setArray(_array_);

        setIndex(_index_);

    }

    @Override
    public Object clone()
    {
        return new AArrayAccessAstExp(
            cloneNode(this._array_),
            cloneNode(this._index_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayAccessAstExp(this);
    }

    public PAstExp getArray()
    {
        return this._array_;
    }

    public void setArray(PAstExp node)
    {
        if(this._array_ != null)
        {
            this._array_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._array_ = node;
    }

    public PAstExp getIndex()
    {
        return this._index_;
    }

    public void setIndex(PAstExp node)
    {
        if(this._index_ != null)
        {
            this._index_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._index_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._array_)
            + toString(this._index_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._array_ == child)
        {
            this._array_ = null;
            return;
        }

        if(this._index_ == child)
        {
            this._index_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._array_ == oldChild)
        {
            setArray((PAstExp) newChild);
            return;
        }

        if(this._index_ == oldChild)
        {
            setIndex((PAstExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
