/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.node;

import goplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABasicAstTypeExp extends PAstTypeExp
{
    private TBasicTypes _basicTypes_;

    public ABasicAstTypeExp()
    {
        // Constructor
    }

    public ABasicAstTypeExp(
        @SuppressWarnings("hiding") TBasicTypes _basicTypes_)
    {
        // Constructor
        setBasicTypes(_basicTypes_);

    }

    @Override
    public Object clone()
    {
        return new ABasicAstTypeExp(
            cloneNode(this._basicTypes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABasicAstTypeExp(this);
    }

    public TBasicTypes getBasicTypes()
    {
        return this._basicTypes_;
    }

    public void setBasicTypes(TBasicTypes node)
    {
        if(this._basicTypes_ != null)
        {
            this._basicTypes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._basicTypes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._basicTypes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._basicTypes_ == child)
        {
            this._basicTypes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._basicTypes_ == oldChild)
        {
            setBasicTypes((TBasicTypes) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
