/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.node;

import goplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABinaryOpAstExp extends PAstExp
{
    private PAstExp _left_;
    private PAstBinaryOp _astBinaryOp_;
    private PAstExp _right_;

    public ABinaryOpAstExp()
    {
        // Constructor
    }

    public ABinaryOpAstExp(
        @SuppressWarnings("hiding") PAstExp _left_,
        @SuppressWarnings("hiding") PAstBinaryOp _astBinaryOp_,
        @SuppressWarnings("hiding") PAstExp _right_)
    {
        // Constructor
        setLeft(_left_);

        setAstBinaryOp(_astBinaryOp_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new ABinaryOpAstExp(
            cloneNode(this._left_),
            cloneNode(this._astBinaryOp_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABinaryOpAstExp(this);
    }

    public PAstExp getLeft()
    {
        return this._left_;
    }

    public void setLeft(PAstExp node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public PAstBinaryOp getAstBinaryOp()
    {
        return this._astBinaryOp_;
    }

    public void setAstBinaryOp(PAstBinaryOp node)
    {
        if(this._astBinaryOp_ != null)
        {
            this._astBinaryOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astBinaryOp_ = node;
    }

    public PAstExp getRight()
    {
        return this._right_;
    }

    public void setRight(PAstExp node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._astBinaryOp_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._astBinaryOp_ == child)
        {
            this._astBinaryOp_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PAstExp) newChild);
            return;
        }

        if(this._astBinaryOp_ == oldChild)
        {
            setAstBinaryOp((PAstBinaryOp) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PAstExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
