/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.node;

import java.util.*;
import goplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABlockAstStm extends PAstStm
{
    private final LinkedList<PAstStm> _astStm_ = new LinkedList<PAstStm>();

    public ABlockAstStm()
    {
        // Constructor
    }

    public ABlockAstStm(
        @SuppressWarnings("hiding") List<?> _astStm_)
    {
        // Constructor
        setAstStm(_astStm_);

    }

    @Override
    public Object clone()
    {
        return new ABlockAstStm(
            cloneList(this._astStm_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlockAstStm(this);
    }

    public LinkedList<PAstStm> getAstStm()
    {
        return this._astStm_;
    }

    public void setAstStm(List<?> list)
    {
        for(PAstStm e : this._astStm_)
        {
            e.parent(null);
        }
        this._astStm_.clear();

        for(Object obj_e : list)
        {
            PAstStm e = (PAstStm) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._astStm_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._astStm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._astStm_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAstStm> i = this._astStm_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAstStm) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
