/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.node;

import java.util.*;
import goplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ACaseAstSwitchCase extends PAstSwitchCase
{
    private final LinkedList<PAstExp> _astExp_ = new LinkedList<PAstExp>();

    public ACaseAstSwitchCase()
    {
        // Constructor
    }

    public ACaseAstSwitchCase(
        @SuppressWarnings("hiding") List<?> _astExp_)
    {
        // Constructor
        setAstExp(_astExp_);

    }

    @Override
    public Object clone()
    {
        return new ACaseAstSwitchCase(
            cloneList(this._astExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACaseAstSwitchCase(this);
    }

    public LinkedList<PAstExp> getAstExp()
    {
        return this._astExp_;
    }

    public void setAstExp(List<?> list)
    {
        for(PAstExp e : this._astExp_)
        {
            e.parent(null);
        }
        this._astExp_.clear();

        for(Object obj_e : list)
        {
            PAstExp e = (PAstExp) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._astExp_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._astExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._astExp_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAstExp> i = this._astExp_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAstExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
