/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.node;

import goplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AExpAstStm extends PAstStm
{
    private PAstExp _astExp_;

    public AExpAstStm()
    {
        // Constructor
    }

    public AExpAstStm(
        @SuppressWarnings("hiding") PAstExp _astExp_)
    {
        // Constructor
        setAstExp(_astExp_);

    }

    @Override
    public Object clone()
    {
        return new AExpAstStm(
            cloneNode(this._astExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpAstStm(this);
    }

    public PAstExp getAstExp()
    {
        return this._astExp_;
    }

    public void setAstExp(PAstExp node)
    {
        if(this._astExp_ != null)
        {
            this._astExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._astExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._astExp_ == child)
        {
            this._astExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._astExp_ == oldChild)
        {
            setAstExp((PAstExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
