/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.node;

import java.util.*;
import goplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AForAstStm extends PAstStm
{
    private PAstStm _init_;
    private PAstExp _condition_;
    private PAstStm _post_;
    private final LinkedList<PAstStm> _body_ = new LinkedList<PAstStm>();

    public AForAstStm()
    {
        // Constructor
    }

    public AForAstStm(
        @SuppressWarnings("hiding") PAstStm _init_,
        @SuppressWarnings("hiding") PAstExp _condition_,
        @SuppressWarnings("hiding") PAstStm _post_,
        @SuppressWarnings("hiding") List<?> _body_)
    {
        // Constructor
        setInit(_init_);

        setCondition(_condition_);

        setPost(_post_);

        setBody(_body_);

    }

    @Override
    public Object clone()
    {
        return new AForAstStm(
            cloneNode(this._init_),
            cloneNode(this._condition_),
            cloneNode(this._post_),
            cloneList(this._body_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForAstStm(this);
    }

    public PAstStm getInit()
    {
        return this._init_;
    }

    public void setInit(PAstStm node)
    {
        if(this._init_ != null)
        {
            this._init_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._init_ = node;
    }

    public PAstExp getCondition()
    {
        return this._condition_;
    }

    public void setCondition(PAstExp node)
    {
        if(this._condition_ != null)
        {
            this._condition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condition_ = node;
    }

    public PAstStm getPost()
    {
        return this._post_;
    }

    public void setPost(PAstStm node)
    {
        if(this._post_ != null)
        {
            this._post_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._post_ = node;
    }

    public LinkedList<PAstStm> getBody()
    {
        return this._body_;
    }

    public void setBody(List<?> list)
    {
        for(PAstStm e : this._body_)
        {
            e.parent(null);
        }
        this._body_.clear();

        for(Object obj_e : list)
        {
            PAstStm e = (PAstStm) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._body_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._init_)
            + toString(this._condition_)
            + toString(this._post_)
            + toString(this._body_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._init_ == child)
        {
            this._init_ = null;
            return;
        }

        if(this._condition_ == child)
        {
            this._condition_ = null;
            return;
        }

        if(this._post_ == child)
        {
            this._post_ = null;
            return;
        }

        if(this._body_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._init_ == oldChild)
        {
            setInit((PAstStm) newChild);
            return;
        }

        if(this._condition_ == oldChild)
        {
            setCondition((PAstExp) newChild);
            return;
        }

        if(this._post_ == oldChild)
        {
            setPost((PAstStm) newChild);
            return;
        }

        for(ListIterator<PAstStm> i = this._body_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAstStm) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
