/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.node;

import goplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AFuncDecAstDecl extends PAstDecl
{
    private PAstFuncDecl _astFuncDecl_;

    public AFuncDecAstDecl()
    {
        // Constructor
    }

    public AFuncDecAstDecl(
        @SuppressWarnings("hiding") PAstFuncDecl _astFuncDecl_)
    {
        // Constructor
        setAstFuncDecl(_astFuncDecl_);

    }

    @Override
    public Object clone()
    {
        return new AFuncDecAstDecl(
            cloneNode(this._astFuncDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncDecAstDecl(this);
    }

    public PAstFuncDecl getAstFuncDecl()
    {
        return this._astFuncDecl_;
    }

    public void setAstFuncDecl(PAstFuncDecl node)
    {
        if(this._astFuncDecl_ != null)
        {
            this._astFuncDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astFuncDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._astFuncDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._astFuncDecl_ == child)
        {
            this._astFuncDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._astFuncDecl_ == oldChild)
        {
            setAstFuncDecl((PAstFuncDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
