/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.node;

import goplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ALitAstExp extends PAstExp
{
    private PAstLiteral _astLiteral_;

    public ALitAstExp()
    {
        // Constructor
    }

    public ALitAstExp(
        @SuppressWarnings("hiding") PAstLiteral _astLiteral_)
    {
        // Constructor
        setAstLiteral(_astLiteral_);

    }

    @Override
    public Object clone()
    {
        return new ALitAstExp(
            cloneNode(this._astLiteral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALitAstExp(this);
    }

    public PAstLiteral getAstLiteral()
    {
        return this._astLiteral_;
    }

    public void setAstLiteral(PAstLiteral node)
    {
        if(this._astLiteral_ != null)
        {
            this._astLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astLiteral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._astLiteral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._astLiteral_ == child)
        {
            this._astLiteral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._astLiteral_ == oldChild)
        {
            setAstLiteral((PAstLiteral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
