/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.node;

import java.util.*;
import goplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ATypeDeclAstStm extends PAstStm
{
    private final LinkedList<PAstTypeDecl> _astTypeDecl_ = new LinkedList<PAstTypeDecl>();

    public ATypeDeclAstStm()
    {
        // Constructor
    }

    public ATypeDeclAstStm(
        @SuppressWarnings("hiding") List<?> _astTypeDecl_)
    {
        // Constructor
        setAstTypeDecl(_astTypeDecl_);

    }

    @Override
    public Object clone()
    {
        return new ATypeDeclAstStm(
            cloneList(this._astTypeDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeDeclAstStm(this);
    }

    public LinkedList<PAstTypeDecl> getAstTypeDecl()
    {
        return this._astTypeDecl_;
    }

    public void setAstTypeDecl(List<?> list)
    {
        for(PAstTypeDecl e : this._astTypeDecl_)
        {
            e.parent(null);
        }
        this._astTypeDecl_.clear();

        for(Object obj_e : list)
        {
            PAstTypeDecl e = (PAstTypeDecl) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._astTypeDecl_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._astTypeDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._astTypeDecl_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAstTypeDecl> i = this._astTypeDecl_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAstTypeDecl) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
