/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.node;

import goplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TAndeq extends Token
{
    public TAndeq()
    {
        super.setText("&=");
    }

    public TAndeq(int line, int pos)
    {
        super.setText("&=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAndeq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAndeq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAndeq text.");
    }
}
