/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.node;

import goplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TMuleq extends Token
{
    public TMuleq()
    {
        super.setText("*=");
    }

    public TMuleq(int line, int pos)
    {
        super.setText("*=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMuleq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMuleq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMuleq text.");
    }
}
