/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.node;

import goplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TRshifteq extends Token
{
    public TRshifteq()
    {
        super.setText(">>=");
    }

    public TRshifteq(int line, int pos)
    {
        super.setText(">>=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRshifteq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRshifteq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRshifteq text.");
    }
}
