/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.node;

import goplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TSubeq extends Token
{
    public TSubeq()
    {
        super.setText("-=");
    }

    public TSubeq(int line, int pos)
    {
        super.setText("-=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSubeq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSubeq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSubeq text.");
    }
}
