all:
	cd bench01 && $(MAKE)
	cd bench02 && $(MAKE)
	cd bench03 && $(MAKE)
	cd bench04 && $(MAKE)
	cd bench05 && $(MAKE)
	cd bench06 && $(MAKE)
	cd bench07 && $(MAKE)

opt:
	cd bench01 && $(MAKE) opt
	cd bench02 && $(MAKE) opt
	cd bench03 && $(MAKE) opt
	cd bench04 && $(MAKE) opt
	cd bench05 && $(MAKE) opt
	cd bench06 && $(MAKE) opt
	cd bench07 && $(MAKE) opt