/* This file was generated by SableCC (http://www.sablecc.org/). */

package goplusplus.lexer;

import java.io.*;
import goplusplus.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 57:
                        {
                            @SuppressWarnings("hiding") Token token = new57(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 58:
                        {
                            @SuppressWarnings("hiding") Token token = new58(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 59:
                        {
                            @SuppressWarnings("hiding") Token token = new59(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 60:
                        {
                            @SuppressWarnings("hiding") Token token = new60(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 61:
                        {
                            @SuppressWarnings("hiding") Token token = new61(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 62:
                        {
                            @SuppressWarnings("hiding") Token token = new62(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 63:
                        {
                            @SuppressWarnings("hiding") Token token = new63(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 64:
                        {
                            @SuppressWarnings("hiding") Token token = new64(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 65:
                        {
                            @SuppressWarnings("hiding") Token token = new65(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 66:
                        {
                            @SuppressWarnings("hiding") Token token = new66(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 67:
                        {
                            @SuppressWarnings("hiding") Token token = new67(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 68:
                        {
                            @SuppressWarnings("hiding") Token token = new68(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 69:
                        {
                            @SuppressWarnings("hiding") Token token = new69(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 70:
                        {
                            @SuppressWarnings("hiding") Token token = new70(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 71:
                        {
                            @SuppressWarnings("hiding") Token token = new71(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 72:
                        {
                            @SuppressWarnings("hiding") Token token = new72(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 73:
                        {
                            @SuppressWarnings("hiding") Token token = new73(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 74:
                        {
                            @SuppressWarnings("hiding") Token token = new74(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 75:
                        {
                            @SuppressWarnings("hiding") Token token = new75(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 76:
                        {
                            @SuppressWarnings("hiding") Token token = new76(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 77:
                        {
                            @SuppressWarnings("hiding") Token token = new77(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 78:
                        {
                            @SuppressWarnings("hiding") Token token = new78(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 79:
                        {
                            @SuppressWarnings("hiding") Token token = new79(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 80:
                        {
                            @SuppressWarnings("hiding") Token token = new80(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 81:
                        {
                            @SuppressWarnings("hiding") Token token = new81(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 82:
                        {
                            @SuppressWarnings("hiding") Token token = new82(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 83:
                        {
                            @SuppressWarnings("hiding") Token token = new83(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 84:
                        {
                            @SuppressWarnings("hiding") Token token = new84(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 85:
                        {
                            @SuppressWarnings("hiding") Token token = new85(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEol(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBreak(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDefault(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFunc(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInterface(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSelect(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCase(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDefer(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGo(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMap(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStruct(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChan(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElse(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGoto(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPackage(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSwitch(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConst(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFallthrough(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRange(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TType(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TContinue(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFor(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TImport(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReturn(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVar(line, pos); }
    Token new27(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBasicTypes(text, line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrint(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrintln(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAppend(line, pos); }
    Token new31(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBoolLit(text, line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAdd(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSub(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMul(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMod(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBitAnd(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBitOr(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaret(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLshift(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRshift(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBitclear(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPluseq(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSubeq(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMuleq(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiveq(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TModeq(line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAndeq(line, pos); }
    Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOreq(line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TXoreq(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLshifteq(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRshifteq(line, pos); }
    Token new53(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBitcleareq(line, pos); }
    Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnd(line, pos); }
    Token new55(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOr(line, pos); }
    Token new56(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReceive(line, pos); }
    Token new57(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIncrement(line, pos); }
    Token new58(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDecrement(line, pos); }
    Token new59(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEq(line, pos); }
    Token new60(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLt(line, pos); }
    Token new61(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGt(line, pos); }
    Token new62(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAssign(line, pos); }
    Token new63(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNot(line, pos); }
    Token new64(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNoteq(line, pos); }
    Token new65(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeq(line, pos); }
    Token new66(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGeq(line, pos); }
    Token new67(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TShortdecl(line, pos); }
    Token new68(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVarargs(line, pos); }
    Token new69(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeftpar(line, pos); }
    Token new70(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeftsq(line, pos); }
    Token new71(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeftcurl(line, pos); }
    Token new72(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new73(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new74(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRightpar(line, pos); }
    Token new75(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRightsq(line, pos); }
    Token new76(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRightcurl(line, pos); }
    Token new77(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemi(line, pos); }
    Token new78(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new79(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLineComment(text, line, pos); }
    Token new80(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlockComment(text, line, pos); }
    Token new81(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIntLit(text, line, pos); }
    Token new82(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFloatLit(text, line, pos); }
    Token new83(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRuneLit(text, line, pos); }
    Token new84(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStringLit(text, line, pos); }
    Token new85(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {34, 34, 6}, {37, 37, 7}, {38, 38, 8}, {39, 39, 9}, {40, 40, 10}, {41, 41, 11}, {42, 42, 12}, {43, 43, 13}, {44, 44, 14}, {45, 45, 15}, {46, 46, 16}, {47, 47, 17}, {48, 48, 18}, {49, 57, 19}, {58, 58, 20}, {59, 59, 21}, {60, 60, 22}, {61, 61, 23}, {62, 62, 24}, {65, 90, 25}, {91, 91, 26}, {93, 93, 27}, {94, 94, 28}, {95, 95, 29}, {97, 97, 30}, {98, 98, 31}, {99, 99, 32}, {100, 100, 33}, {101, 101, 34}, {102, 102, 35}, {103, 103, 36}, {104, 104, 37}, {105, 105, 38}, {106, 108, 37}, {109, 109, 39}, {110, 111, 37}, {112, 112, 40}, {113, 113, 37}, {114, 114, 41}, {115, 115, 42}, {116, 116, 43}, {117, 117, 37}, {118, 118, 44}, {119, 122, 37}, {123, 123, 45}, {124, 124, 46}, {125, 125, 47}, },
            {},
            {},
            {{10, 10, 48}, },
            {},
            {{61, 61, 49}, },
            {{9, 9, 50}, {10, 10, 51}, {13, 13, 52}, {32, 33, 50}, {34, 34, 53}, {35, 255, 50}, },
            {{61, 61, 54}, },
            {{38, 38, 55}, {61, 61, 56}, {94, 94, 57}, },
            {{9, 9, 58}, {10, 10, 59}, {13, 13, 60}, {32, 38, 58}, {39, 39, 61}, {40, 91, 58}, {92, 92, 62}, {93, 255, 58}, },
            {},
            {},
            {{61, 61, 63}, },
            {{43, 43, 64}, {61, 61, 65}, },
            {},
            {{45, 45, 66}, {61, 61, 67}, },
            {{46, 46, 68}, {48, 57, 69}, },
            {{42, 42, 70}, {47, 47, 71}, {61, 61, 72}, },
            {{46, 46, 73}, {48, 55, 74}, {56, 57, 75}, {88, 88, 76}, {120, 120, 77}, },
            {{46, 46, 73}, {48, 57, 78}, },
            {{61, 61, 79}, },
            {},
            {{45, 45, 80}, {60, 60, 81}, {61, 61, 82}, },
            {{61, 61, 83}, },
            {{61, 61, 84}, {62, 62, 85}, },
            {{48, 57, 86}, {65, 90, 87}, {95, 95, 88}, {97, 122, 89}, },
            {},
            {},
            {{61, 61, 90}, },
            {{48, 122, -27}, },
            {{48, 95, -27}, {97, 111, 89}, {112, 112, 91}, {113, 122, 89}, },
            {{48, 95, -27}, {97, 110, 89}, {111, 111, 92}, {112, 113, 89}, {114, 114, 93}, {115, 122, 89}, },
            {{48, 95, -27}, {97, 97, 94}, {98, 103, 89}, {104, 104, 95}, {105, 110, 89}, {111, 111, 96}, {112, 122, 89}, },
            {{48, 95, -27}, {97, 100, 89}, {101, 101, 97}, {102, 122, 89}, },
            {{48, 95, -27}, {97, 107, 89}, {108, 108, 98}, {109, 122, 89}, },
            {{48, 95, -27}, {97, 97, 99}, {98, 107, 89}, {108, 108, 100}, {109, 110, 89}, {111, 111, 101}, {112, 116, 89}, {117, 117, 102}, {118, 122, 89}, },
            {{48, 110, -33}, {111, 111, 103}, {112, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 95, -27}, {97, 101, 89}, {102, 102, 104}, {103, 108, 89}, {109, 109, 105}, {110, 110, 106}, {111, 122, 89}, },
            {{48, 95, -27}, {97, 97, 107}, {98, 122, 89}, },
            {{48, 95, -27}, {97, 97, 108}, {98, 113, 89}, {114, 114, 109}, {115, 122, 89}, },
            {{48, 95, -27}, {97, 97, 110}, {98, 100, 89}, {101, 101, 111}, {102, 116, 89}, {117, 117, 112}, {118, 122, 89}, },
            {{48, 100, -35}, {101, 101, 113}, {102, 115, 89}, {116, 116, 114}, {117, 118, 89}, {119, 119, 115}, {120, 122, 89}, },
            {{48, 95, -27}, {97, 113, 89}, {114, 114, 116}, {115, 120, 89}, {121, 121, 117}, {122, 122, 89}, },
            {{48, 95, -27}, {97, 97, 118}, {98, 122, 89}, },
            {},
            {{61, 61, 119}, {124, 124, 120}, },
            {},
            {},
            {},
            {{9, 255, -8}, },
            {{9, 255, -8}, },
            {{9, 9, 50}, {10, 10, 121}, {13, 255, -8}, },
            {},
            {},
            {},
            {},
            {{61, 61, 122}, },
            {{9, 9, 123}, {10, 13, -11}, {32, 38, 123}, {39, 39, 124}, {40, 255, 123}, },
            {{9, 38, -60}, {39, 39, 61}, {40, 255, 123}, },
            {{9, 9, 123}, {10, 10, 125}, {13, 255, -61}, },
            {},
            {{9, 13, -60}, {32, 33, 123}, {34, 34, 126}, {35, 38, 123}, {39, 39, 127}, {40, 91, 123}, {92, 92, 128}, {93, 96, 123}, {97, 97, 129}, {98, 98, 130}, {99, 101, 123}, {102, 102, 131}, {103, 109, 123}, {110, 110, 132}, {111, 113, 123}, {114, 114, 133}, {115, 115, 123}, {116, 116, 134}, {117, 117, 123}, {118, 118, 135}, {119, 255, 123}, },
            {},
            {},
            {},
            {},
            {},
            {{46, 46, 136}, },
            {{48, 57, 69}, },
            {{0, 41, 137}, {42, 42, 138}, {43, 255, 137}, },
            {{0, 9, 139}, {11, 12, 139}, {14, 255, 139}, },
            {},
            {{48, 57, 140}, },
            {{46, 57, -20}, },
            {{46, 46, 73}, {48, 57, 75}, },
            {{48, 57, 141}, {65, 70, 142}, {97, 102, 143}, },
            {{48, 102, -78}, },
            {{46, 57, -21}, },
            {},
            {},
            {{61, 61, 144}, },
            {},
            {},
            {},
            {{61, 61, 145}, },
            {{48, 122, -27}, },
            {{48, 122, -27}, },
            {{48, 122, -27}, },
            {{48, 122, -27}, },
            {},
            {{48, 111, -32}, {112, 112, 146}, {113, 122, 89}, },
            {{48, 110, -33}, {111, 111, 147}, {112, 122, 89}, },
            {{48, 100, -35}, {101, 101, 148}, {102, 122, 89}, },
            {{48, 95, -27}, {97, 114, 89}, {115, 115, 149}, {116, 122, 89}, },
            {{48, 95, -27}, {97, 97, 150}, {98, 122, 89}, },
            {{48, 95, -27}, {97, 109, 89}, {110, 110, 151}, {111, 122, 89}, },
            {{48, 101, -40}, {102, 102, 152}, {103, 122, 89}, },
            {{48, 114, -96}, {115, 115, 153}, {116, 122, 89}, },
            {{48, 107, -36}, {108, 108, 154}, {109, 122, 89}, },
            {{48, 110, -33}, {111, 111, 155}, {112, 122, 89}, },
            {{48, 113, -45}, {114, 114, 156}, {115, 122, 89}, },
            {{48, 109, -98}, {110, 110, 157}, {111, 122, 89}, },
            {{48, 95, -27}, {97, 115, 89}, {116, 116, 158}, {117, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 111, -32}, {112, 112, 159}, {113, 122, 89}, },
            {{48, 115, -105}, {116, 116, 160}, {117, 122, 89}, },
            {{48, 111, -32}, {112, 112, 161}, {113, 122, 89}, },
            {{48, 95, -27}, {97, 98, 89}, {99, 99, 162}, {100, 122, 89}, },
            {{48, 95, -27}, {97, 104, 89}, {105, 105, 163}, {106, 122, 89}, },
            {{48, 109, -98}, {110, 110, 164}, {111, 122, 89}, },
            {{48, 115, -105}, {116, 116, 165}, {117, 122, 89}, },
            {{48, 109, -98}, {110, 110, 166}, {111, 122, 89}, },
            {{48, 107, -36}, {108, 108, 167}, {109, 122, 89}, },
            {{48, 113, -45}, {114, 114, 168}, {115, 122, 89}, },
            {{48, 104, -111}, {105, 105, 169}, {106, 122, 89}, },
            {{48, 95, -27}, {97, 116, 89}, {117, 117, 170}, {118, 122, 89}, },
            {{48, 111, -32}, {112, 112, 171}, {113, 122, 89}, },
            {{48, 113, -45}, {114, 114, 172}, {115, 122, 89}, },
            {},
            {},
            {{9, 255, -8}, },
            {},
            {{9, 255, -61}, },
            {},
            {{9, 255, -61}, },
            {{9, 255, -60}, },
            {{39, 39, 173}, },
            {{9, 255, -60}, },
            {{9, 255, -60}, },
            {{9, 255, -60}, },
            {{9, 255, -60}, },
            {{9, 255, -60}, },
            {{9, 255, -60}, },
            {{9, 255, -60}, },
            {{9, 255, -60}, },
            {},
            {{0, 255, -72}, },
            {{0, 42, -72}, {43, 46, 137}, {47, 47, 174}, {48, 255, 137}, },
            {{0, 255, -73}, },
            {{48, 57, 140}, },
            {{48, 102, -78}, },
            {{48, 102, -78}, },
            {{48, 102, -78}, },
            {},
            {},
            {{48, 100, -35}, {101, 101, 175}, {102, 122, 89}, },
            {{48, 107, -36}, {108, 108, 176}, {109, 122, 89}, },
            {{48, 95, -27}, {97, 97, 177}, {98, 122, 89}, },
            {{48, 100, -35}, {101, 101, 178}, {102, 122, 89}, },
            {{48, 109, -98}, {110, 110, 179}, {111, 122, 89}, },
            {{48, 114, -96}, {115, 115, 180}, {116, 116, 181}, {117, 122, 89}, },
            {{48, 95, -27}, {97, 97, 182}, {98, 100, 89}, {101, 101, 183}, {102, 122, 89}, },
            {{48, 100, -35}, {101, 101, 184}, {102, 122, 89}, },
            {{48, 107, -36}, {108, 108, 185}, {109, 114, 89}, {115, 115, 186}, {116, 122, 89}, },
            {{48, 95, -27}, {97, 97, 187}, {98, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 98, -110}, {99, 99, 188}, {100, 122, 89}, },
            {{48, 110, -33}, {111, 111, 189}, {112, 122, 89}, },
            {{48, 110, -33}, {111, 111, 190}, {112, 122, 89}, },
            {{48, 100, -35}, {101, 101, 191}, {102, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 95, -27}, {97, 106, 89}, {107, 107, 192}, {108, 122, 89}, },
            {{48, 109, -98}, {110, 110, 193}, {111, 122, 89}, },
            {{48, 95, -27}, {97, 102, 89}, {103, 103, 194}, {104, 122, 89}, },
            {{48, 116, -118}, {117, 117, 195}, {118, 122, 89}, },
            {{48, 100, -35}, {101, 101, 196}, {102, 122, 89}, },
            {{48, 100, -35}, {101, 101, 197}, {102, 122, 89}, },
            {{48, 104, -111}, {105, 105, 198}, {106, 116, 89}, {117, 117, 199}, {118, 122, 89}, },
            {{48, 115, -105}, {116, 116, 200}, {117, 122, 89}, },
            {{48, 100, -35}, {101, 101, 201}, {102, 122, 89}, },
            {{48, 100, -35}, {101, 101, 202}, {102, 122, 89}, },
            {{48, 122, -27}, },
            {},
            {{0, 255, -72}, },
            {{48, 109, -98}, {110, 110, 203}, {111, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 106, -164}, {107, 107, 204}, {108, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 122, -27}, },
            {{48, 115, -105}, {116, 116, 205}, {117, 122, 89}, },
            {{48, 104, -111}, {105, 105, 206}, {106, 122, 89}, },
            {{48, 116, -118}, {117, 117, 207}, {118, 122, 89}, },
            {{48, 113, -45}, {114, 114, 208}, {115, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 115, -105}, {116, 116, 209}, {117, 122, 89}, },
            {{48, 100, -35}, {101, 101, 210}, {102, 122, 89}, },
            {{48, 115, -105}, {116, 116, 211}, {117, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 122, -27}, },
            {{48, 113, -45}, {114, 114, 212}, {115, 122, 89}, },
            {{48, 113, -45}, {114, 114, 213}, {115, 122, 89}, },
            {{48, 95, -27}, {97, 97, 214}, {98, 122, 89}, },
            {{48, 115, -105}, {116, 116, 215}, {117, 122, 89}, },
            {{48, 100, -35}, {101, 101, 216}, {102, 122, 89}, },
            {{48, 113, -45}, {114, 114, 217}, {115, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 98, -110}, {99, 99, 218}, {100, 122, 89}, },
            {{48, 109, -98}, {110, 110, 219}, {111, 122, 89}, },
            {{48, 98, -110}, {99, 99, 220}, {100, 122, 89}, },
            {{48, 98, -110}, {99, 99, 221}, {100, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 122, -27}, },
            {{48, 95, -27}, {97, 99, 89}, {100, 100, 222}, {101, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 122, -27}, },
            {{48, 109, -98}, {110, 110, 223}, {111, 122, 89}, },
            {{48, 107, -36}, {108, 108, 224}, {109, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 95, -27}, {97, 103, 89}, {104, 104, 225}, {105, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 53, 86}, {54, 54, 226}, {55, 57, 86}, {65, 122, -27}, },
            {{48, 115, -105}, {116, 116, 227}, {117, 122, 89}, },
            {{48, 101, -40}, {102, 102, 228}, {103, 122, 89}, },
            {{48, 102, -166}, {103, 103, 229}, {104, 122, 89}, },
            {{48, 107, -36}, {108, 108, 230}, {109, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 109, -98}, {110, 110, 231}, {111, 122, 89}, },
            {{48, 115, -105}, {116, 116, 232}, {117, 122, 89}, },
            {{48, 102, -166}, {103, 103, 233}, {104, 122, 89}, },
            {{48, 115, -105}, {116, 116, 234}, {117, 122, 89}, },
            {{48, 103, -211}, {104, 104, 235}, {105, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 116, -118}, {117, 117, 236}, {118, 122, 89}, },
            {{48, 115, -105}, {116, 116, 237}, {117, 122, 89}, },
            {{48, 113, -45}, {114, 114, 238}, {115, 122, 89}, },
            {{48, 51, 86}, {52, 52, 239}, {53, 57, 86}, {65, 122, -27}, },
            {{48, 122, -27}, },
            {{48, 95, -27}, {97, 97, 240}, {98, 122, 89}, },
            {{48, 100, -35}, {101, 101, 241}, {102, 122, 89}, },
            {{48, 109, -98}, {110, 110, 242}, {111, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 122, -27}, },
            {{48, 122, -27}, },
            {{48, 122, -27}, },
            {{48, 122, -27}, },
            {{48, 100, -35}, {101, 101, 243}, {102, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 110, -33}, {111, 111, 244}, {112, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 98, -110}, {99, 99, 245}, {100, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 122, -27}, },
            {{48, 122, -27}, },
            {{48, 116, -118}, {117, 117, 246}, {118, 122, 89}, },
            {{48, 100, -35}, {101, 101, 247}, {102, 122, 89}, },
            {{48, 102, -166}, {103, 103, 248}, {104, 122, 89}, },
            {{48, 122, -27}, },
            {{48, 103, -211}, {104, 104, 249}, {105, 122, 89}, },
            {{48, 122, -27}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {83, 1, 0, 0, 1, 63, -1, 36, 37, -1, 69, 74, 34, 32, 72, 33, 73, 35, 81, 81, 78, 77, 60, 62, 61, 85, 70, 75, 39, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 71, 38, 76, 0, 64, -1, -1, -1, 84, 47, 54, 48, 42, -1, -1, -1, 84, -1, 45, 57, 43, 58, 44, -1, 82, -1, 79, 46, 82, 81, -1, -1, -1, 81, 67, 56, 40, 65, 59, 66, 41, 85, 85, 85, 85, 50, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 9, 19, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 49, 55, -1, 53, -1, 83, -1, -1, 83, -1, -1, -1, -1, -1, -1, -1, -1, 68, -1, -1, 79, 82, 81, 81, 81, 51, 52, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 23, 85, 85, 85, 27, 10, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 26, 83, 80, 85, 27, 85, 7, 12, 85, 85, 85, 85, 13, 85, 85, 85, 4, 14, 85, 85, 85, 85, 85, 85, 27, 85, 85, 85, 85, 31, 21, 85, 2, 17, 85, 85, 8, 85, 31, 85, 85, 85, 85, 28, 20, 85, 85, 85, 85, 85, 30, 85, 85, 85, 85, 24, 85, 85, 85, 25, 6, 27, 11, 16, 85, 3, 85, 27, 85, 15, 29, 22, 85, 85, 85, 5, 85, 18, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
